# Generated by Django 3.2.5 on 2021-07-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_rename_room_message_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
